{
 "title": "Core Banking - Visão de Performance",
 "tags": [
  "core-banking",
  "performance",
  "fiap-itau"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"banking-api\"}[15s]))",
     "legendFormat": "TPS Global"
    }
   ]
  },
  {
   "title": "HTTP Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"banking-api\"}[30s])) by (le))",
     "legendFormat": "P50 (Mediana)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"banking-api\"}[30s])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"banking-api\"}[30s])) by (le))",
     "legendFormat": "P99 (Cauda Longa)"
    }
   ]
  },
  {
   "title": "Active Connections (HikariCP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pool=\"HikariPool-1\"}",
     "legendFormat": "Ativas"
    },
    {
     "expr": "hikaricp_connections_pending{pool=\"HikariPool-1\"}",
     "legendFormat": "Pendentes (Espera)"
    },
    {
     "expr": "hikaricp_connections_idle{pool=\"HikariPool-1\"}",
     "legendFormat": "Ociosas (Idle)"
    }
   ]
  },
  {
   "title": "Database Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\".*extrato.*\"}[30s])) by (le))",
     "legendFormat": "P99 Consulta Extrato (Postgres)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\".*saldo.*\"}[30s])) by (le))",
     "legendFormat": "P99 Consulta Saldo (PK Indexada)"
    }
   ]
  }
 ]
}